version: "3.7"

services:

    profile-be:
        restart: unless-stopped
        build:
            context: .
            dockerfile: Dockerfile
        image: cantico-profile-be
        ports:
            - "${BE_PORT}:8080"
        env_file:
            - .env
